### ISSUE TITLE
[BUG] - Surface number 0 is used in Cell definition

### ISSUE THREAD

**Issue by shimwell** [GEOUNED-org/GEOUNED#201]
# Describe the bug
Looks like the surface numbers used in the cell definition don't match the surface numbers.

# Expected behavior
Surface ids start at 1 but the cells use surface with id 0

# Error message
No error in geound but will not work in transport

# Screenshots
Easy to see in the openmc python code as VS code highlights the undefined variables ```S0```
![Screenshot from 2024-05-27 11-45-36](https://github.com/GEOUNED-org/GEOUNED/assets/8583900/e337f8cb-105b-4d19-a8a8-2dd384f4acdd)

Also in the mcnp and other codes
![Screenshot from 2024-05-27 11-48-04](https://github.com/GEOUNED-org/GEOUNED/assets/8583900/6d03902f-c372-4f04-ad30-dbc81dec70b1)
ssets/8583900/73a3c1cf-6175-4fb5-a6fa-61da5d51ce50)

# Please complete the following information):
 - OS: linux
 - GEOUNEd dev
 - Python version 3.11

# Additional context
I should add some tests to check cells don't use no existent surface numbers

**Comment by akolsek** [comment]
The step model appears to contain splines. Please double check.

**Comment by KBGrammer** [comment]
This same error pops up for me during simplification and I've seen it in the resulting MCNP file. I think it might also cause issues during void generation.
```
File "~/GEOUNED-1.1.0/src/geouned/GEOUNED/utils/boolean_solids.py", line 253, in build_c_table_from_solids
    if type(surfaces[surfaceList[0]]) is GeounedSurface:
KeyError: 0
```
My model does have spline surfaces. Are splines becoming a surface number of 0 in cell definitions?

Is there a way to make geouned soft-error on things? A "this is a spline, ignoring it, moving on" warning rather than a crash would be good.

I patched my local version to try to put a bandaid on it in build_c_table_from_solids, but 0 index keeps popping up in new spots. It probably needs cleaned up earlier than I'm trying to clean it up.

**Comment by KBGrammer** [comment]
#204 would help as long as debug is on, right? Or would log files have enough information to show you which cell ID it failed on? It would let you easily see which cell failed and skip it on the next try. However, that becomes problematic if if fails on cell 100 of 1000 and then fails on 150 of 999 and then fails on 250 of 998, etc. You could do simple parallel and split it manually with the input and run 10 sets to find 10 failures, remove those, repeat, though.

It would be great if you could just tell it to work on a conversion and just flag/warn you about failed cells. If I've got a big model, it makes it easy to run overnight and come back tomorrow to see which bodies failed to convert, decide if I care, and fix it if I need to.

The 0 surface comes up a lot. I've been modifying the code locally to put in bandaids to try to get around them and then it pops up and causes problems elsewhere.

**Comment by alexvalentine94** [comment]
solving in #210
