### ISSUE TITLE
[Feature request] - allow exporting of void geometry to separate STP file 

### ISSUE THREAD

**Issue by shimwell** [GEOUNED-org/GEOUNED#208]
# Is your feature request related to a problem? Please describe.
I was getting a glimpse of @AlvaroCubi working with geouned today. He makes use of the ```settings.debug=True``` to export decomposed geometry in stp format. We both think there is no debug setting equivalent for exporting void cells to stp file.

# Describe the solution you'd like
We would like to export the void cells to a separate stp file so that manual inspection can take place

**Comment by psauvan** [comment]
This is not feasible since void cells are not solid CAD cells. Void cells are only logical CGS cell definition.
This can be done only with enclosures cells (since there are defined in the Step file as a solid).
The other option is to reconstruct the void cell using the reverse function (CSG to CAD) of GEOUNED. But this alternative will fail a lot since voids can be complex and reverse function is not so stable to translate such complex cells
